version: "3.8"

services:
  mlops_app:
    build: .
    container_name: mlops_app_container
    ports:
      - "8000:8000"  # Expose port 8000 (change if your app uses another)
    restart: always
    environment:
      - ENV=production
    volumes:
      - .:/app